// <auto-generated />
using System;
using Aura.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Aura.Infrastructure.Migrations
{
    [DbContext(typeof(AuraDbContext))]
    partial class AuraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aura.Domain.Entities.AllocationPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ResponseWindowDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Round1Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AllocationPeriods");
                });

            modelBuilder.Entity("Aura.Domain.Entities.Campus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Campuses");
                });

            modelBuilder.Entity("Aura.Domain.Entities.DormAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AllocationPeriodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DormitoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastPreCloseWarningSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllocationPeriodId");

                    b.HasIndex("DormitoryId");

                    b.HasIndex("AllocationPeriodId", "Round");

                    b.HasIndex("UserId", "AllocationPeriodId")
                        .IsUnique()
                        .HasDatabaseName("IX_DormAllocation_ActiveOnePerUserPeriod")
                        .HasFilter("\"Status\" IN ('Pending', 'Accepted')");

                    b.ToTable("DormAllocations");
                });

            modelBuilder.Entity("Aura.Domain.Entities.DormPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationPeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DormitoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllocationPeriodId");

                    b.HasIndex("DormitoryId");

                    b.HasIndex("UserId", "AllocationPeriodId", "DormitoryId")
                        .IsUnique();

                    b.HasIndex("UserId", "AllocationPeriodId", "Rank")
                        .IsUnique();

                    b.ToTable("DormPreferences");
                });

            modelBuilder.Entity("Aura.Domain.Entities.Dormitory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.ToTable("Dormitories");
                });

            modelBuilder.Entity("Aura.Domain.Entities.EmailConfirmationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Code");

                    b.ToTable("EmailConfirmationCodes");
                });

            modelBuilder.Entity("Aura.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("Aura.Domain.Entities.FacultyRoomAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationPeriodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllocationPeriodId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("RoomId", "AllocationPeriodId")
                        .IsUnique();

                    b.ToTable("FacultyRoomAllocations");
                });

            modelBuilder.Entity("Aura.Domain.Entities.GroupInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InviteeUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InviterUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("InviteeUserId");

                    b.HasIndex("GroupId", "InviteeUserId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("GroupInvitations", (string)null);
                });

            modelBuilder.Entity("Aura.Domain.Entities.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Category", "DisplayOrder", "IsActive");

                    b.ToTable("Interests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0001-0001-0001-000000000001"),
                            Category = "sports",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "Football",
                            Slug = "football"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0001-0001-0001-000000000002"),
                            Category = "sports",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Label = "Basketball",
                            Slug = "basketball"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0001-0001-0001-000000000003"),
                            Category = "sports",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Label = "Tennis",
                            Slug = "tennis"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0001-0001-0001-000000000004"),
                            Category = "sports",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            Label = "Running",
                            Slug = "running"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0001-0001-0001-000000000005"),
                            Category = "sports",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            Label = "Gym",
                            Slug = "gym"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0001-0001-0001-000000000006"),
                            Category = "sports",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsActive = true,
                            Label = "Swimming",
                            Slug = "swimming"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0001-0001-0001-000000000007"),
                            Category = "sports",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsActive = true,
                            Label = "Hiking",
                            Slug = "hiking"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0001-0001-0001-000000000008"),
                            Category = "sports",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsActive = true,
                            Label = "Cycling",
                            Slug = "cycling"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0002-0002-0002-000000000001"),
                            Category = "entertainment",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "Movies",
                            Slug = "movies"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0002-0002-0002-000000000002"),
                            Category = "entertainment",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Label = "TV Series",
                            Slug = "tv-series"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0002-0002-0002-000000000003"),
                            Category = "entertainment",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Label = "Anime",
                            Slug = "anime"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0002-0002-0002-000000000004"),
                            Category = "entertainment",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            Label = "Gaming",
                            Slug = "gaming"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0002-0002-0002-000000000005"),
                            Category = "entertainment",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            Label = "Board Games",
                            Slug = "board-games"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0002-0002-0002-000000000006"),
                            Category = "entertainment",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsActive = true,
                            Label = "Podcasts",
                            Slug = "podcasts"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0002-0002-0002-000000000007"),
                            Category = "entertainment",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsActive = true,
                            Label = "Live Music",
                            Slug = "live-music"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0002-0002-0002-000000000008"),
                            Category = "entertainment",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsActive = true,
                            Label = "Reading",
                            Slug = "reading"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0003-0003-0003-000000000001"),
                            Category = "arts",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "Drawing",
                            Slug = "drawing"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0003-0003-0003-000000000002"),
                            Category = "arts",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Label = "Photography",
                            Slug = "photography"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0003-0003-0003-000000000003"),
                            Category = "arts",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Label = "Writing",
                            Slug = "writing"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0003-0003-0003-000000000004"),
                            Category = "arts",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            Label = "Playing music",
                            Slug = "music-playing"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0003-0003-0003-000000000005"),
                            Category = "arts",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            Label = "Theater",
                            Slug = "theater"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0003-0003-0003-000000000006"),
                            Category = "arts",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsActive = true,
                            Label = "Crafts",
                            Slug = "crafts"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0004-0004-0004-000000000001"),
                            Category = "academic",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "Programming",
                            Slug = "programming"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0004-0004-0004-000000000002"),
                            Category = "academic",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Label = "Science",
                            Slug = "science"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0004-0004-0004-000000000003"),
                            Category = "academic",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Label = "History",
                            Slug = "history"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0004-0004-0004-000000000004"),
                            Category = "academic",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            Label = "Languages",
                            Slug = "languages"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0004-0004-0004-000000000005"),
                            Category = "academic",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            Label = "Mathematics",
                            Slug = "mathematics"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0005-0005-0005-000000000001"),
                            Category = "lifestyle",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "Cooking",
                            Slug = "cooking"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0005-0005-0005-000000000002"),
                            Category = "lifestyle",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Label = "Traveling",
                            Slug = "traveling"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0005-0005-0005-000000000003"),
                            Category = "lifestyle",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Label = "Volunteering",
                            Slug = "volunteering"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0005-0005-0005-000000000004"),
                            Category = "lifestyle",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            Label = "Pets",
                            Slug = "pets"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0005-0005-0005-000000000005"),
                            Category = "lifestyle",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            Label = "Fashion",
                            Slug = "fashion"
                        });
                });

            modelBuilder.Entity("Aura.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("DormitoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DormitoryId", "Number")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Aura.Domain.Entities.RoomAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationPeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoommateGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllocationPeriodId");

                    b.HasIndex("RoommateGroupId");

                    b.HasIndex("RoomId", "AllocationPeriodId")
                        .HasDatabaseName("IX_RoomAssignments_RoomId_AllocationPeriodId");

                    b.HasIndex("UserId", "AllocationPeriodId")
                        .IsUnique()
                        .HasDatabaseName("IX_RoomAssignments_UserId_AllocationPeriodId");

                    b.ToTable("RoomAssignments");
                });

            modelBuilder.Entity("Aura.Domain.Entities.RoommateGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationPeriodId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnchorRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DisbandedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DormitoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeaderUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomSizePreference")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnchorRoomId");

                    b.HasIndex("AllocationPeriodId", "Status");

                    b.ToTable("RoommateGroups", (string)null);
                });

            modelBuilder.Entity("Aura.Domain.Entities.SpotifySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AvgDanceability")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AvgEnergy")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AvgValence")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("TopArtists")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("TopGenres")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("TopTracks")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FetchedAt")
                        .IsDescending(false, true);

                    b.ToTable("SpotifySnapshots", (string)null);
                });

            modelBuilder.Entity("Aura.Domain.Entities.StudentEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)");

                    b.Property<DateTime?>("LastEmbeddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentEmbeddings", (string)null);
                });

            modelBuilder.Entity("Aura.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CleanlinessLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GuestFrequency")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string>("InterestSlugs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("InterestsCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LifestyleCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NoiseTolerance")
                        .HasColumnType("integer");

                    b.Property<int?>("SleepSchedule")
                        .HasColumnType("integer");

                    b.Property<int?>("SmokingHabit")
                        .HasColumnType("integer");

                    b.Property<string>("SpotifyAccessToken")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("SpotifyConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpotifyRefreshToken")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.PrimitiveCollection<string>("SpotifyScopes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("SpotifyTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StudyLocation")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TipiAgreeableness")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<string>("TipiAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("TipiCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TipiConscientiousness")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TipiEmotionalStability")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TipiExtraversion")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TipiOpenness")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WakeUpTime")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudentProfile_Cleanliness_Range", "\"CleanlinessLevel\" IS NULL OR \"CleanlinessLevel\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Aura.Domain.Entities.StudentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationPeriodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MatriculationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllocationPeriodId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("MatriculationCode", "AllocationPeriodId")
                        .IsUnique();

                    b.HasIndex("UserId", "AllocationPeriodId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("StudentRecords");
                });

            modelBuilder.Entity("Aura.Domain.Entities.UpgradeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationPeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllocationPeriodId");

                    b.HasIndex("UserId", "AllocationPeriodId")
                        .IsUnique()
                        .HasDatabaseName("IX_UpgradeRequest_OneActivePerUserPeriod")
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("UpgradeRequests");
                });

            modelBuilder.Entity("Aura.Domain.Entities.UpgradeRequestTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DormitoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("UpgradeRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DormitoryId");

                    b.HasIndex("UpgradeRequestId", "DormitoryId")
                        .IsUnique();

                    b.HasIndex("UpgradeRequestId", "Rank")
                        .IsUnique();

                    b.ToTable("UpgradeRequestTargets");
                });

            modelBuilder.Entity("Aura.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MatriculationCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FacultyId");

                    b.HasIndex("MatriculationCode")
                        .IsUnique()
                        .HasFilter("\"MatriculationCode\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aura.Domain.Entities.DormAllocation", b =>
                {
                    b.HasOne("Aura.Domain.Entities.AllocationPeriod", "AllocationPeriod")
                        .WithMany()
                        .HasForeignKey("AllocationPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.Dormitory", "Dormitory")
                        .WithMany()
                        .HasForeignKey("DormitoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AllocationPeriod");

                    b.Navigation("Dormitory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aura.Domain.Entities.DormPreference", b =>
                {
                    b.HasOne("Aura.Domain.Entities.AllocationPeriod", "AllocationPeriod")
                        .WithMany()
                        .HasForeignKey("AllocationPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.Dormitory", "Dormitory")
                        .WithMany()
                        .HasForeignKey("DormitoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllocationPeriod");

                    b.Navigation("Dormitory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aura.Domain.Entities.Dormitory", b =>
                {
                    b.HasOne("Aura.Domain.Entities.Campus", "Campus")
                        .WithMany("Dormitories")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("Aura.Domain.Entities.EmailConfirmationCode", b =>
                {
                    b.HasOne("Aura.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aura.Domain.Entities.FacultyRoomAllocation", b =>
                {
                    b.HasOne("Aura.Domain.Entities.AllocationPeriod", "AllocationPeriod")
                        .WithMany()
                        .HasForeignKey("AllocationPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AllocationPeriod");

                    b.Navigation("Faculty");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Aura.Domain.Entities.Room", b =>
                {
                    b.HasOne("Aura.Domain.Entities.Dormitory", "Dormitory")
                        .WithMany("Rooms")
                        .HasForeignKey("DormitoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("Aura.Domain.Entities.RoomAssignment", b =>
                {
                    b.HasOne("Aura.Domain.Entities.AllocationPeriod", "AllocationPeriod")
                        .WithMany()
                        .HasForeignKey("AllocationPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.RoommateGroup", "RoommateGroup")
                        .WithMany()
                        .HasForeignKey("RoommateGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aura.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllocationPeriod");

                    b.Navigation("Room");

                    b.Navigation("RoommateGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aura.Domain.Entities.RoommateGroup", b =>
                {
                    b.HasOne("Aura.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("AnchorRoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("Aura.Domain.Entities.GroupMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("GroupId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("GroupId", "UserId");

                            b1.ToTable("GroupMembers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GroupId");
                        });

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Aura.Domain.Entities.StudentRecord", b =>
                {
                    b.HasOne("Aura.Domain.Entities.AllocationPeriod", "AllocationPeriod")
                        .WithMany()
                        .HasForeignKey("AllocationPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AllocationPeriod");

                    b.Navigation("Faculty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aura.Domain.Entities.UpgradeRequest", b =>
                {
                    b.HasOne("Aura.Domain.Entities.AllocationPeriod", "AllocationPeriod")
                        .WithMany()
                        .HasForeignKey("AllocationPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AllocationPeriod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aura.Domain.Entities.UpgradeRequestTarget", b =>
                {
                    b.HasOne("Aura.Domain.Entities.Dormitory", "Dormitory")
                        .WithMany()
                        .HasForeignKey("DormitoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aura.Domain.Entities.UpgradeRequest", "UpgradeRequest")
                        .WithMany("Targets")
                        .HasForeignKey("UpgradeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dormitory");

                    b.Navigation("UpgradeRequest");
                });

            modelBuilder.Entity("Aura.Domain.Entities.User", b =>
                {
                    b.HasOne("Aura.Domain.Entities.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Aura.Domain.Entities.Campus", b =>
                {
                    b.Navigation("Dormitories");
                });

            modelBuilder.Entity("Aura.Domain.Entities.Dormitory", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Aura.Domain.Entities.UpgradeRequest", b =>
                {
                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
